name: ShellCheck

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master
      - dev
      - staging

permissions:
  contents: read

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          format: gcc
          severity: style

